version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mvp-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123@abc
      - POSTGRES_DB=mvpdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mvpdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: mvp-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.profiles.active": "docker",
        "spring.datasource.url": "jdbc:postgresql://db:5432/mvpdb",
        "spring.datasource.username": "postgres",
        "spring.datasource.password": "123@abc",
        "spring.jpa.database-platform": "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "api.security.token.secret": "cd82380e957f4f3e97e6e6aa733c3b2f1489cf60b5248913bfbff29c0ea8f7c7",
        "app.crypto.secret-key": "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
      }'

volumes:
  postgres_data:

